
import controlador.ContactoADO;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import modelo.Contacto;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Informática
 */
public class Libreta extends javax.swing.JFrame {

    /**
     * Creates new form Libreta
     */
    public Libreta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jInternalFrameFormulario = new javax.swing.JInternalFrame();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextNombre = new javax.swing.JTextField();
        jTextCorreo = new javax.swing.JTextField();
        jTextTelefono = new javax.swing.JTextField();
        jTextApellido = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jButton6 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuContacto = new javax.swing.JMenu();
        jMenuItemFormulario = new javax.swing.JMenuItem();
        jMenuItemReporte = new javax.swing.JMenuItem();
        jMenuSalir = new javax.swing.JMenu();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mis Contactos");
        setPreferredSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        setSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jInternalFrameFormulario.setTitle("Formulario - Contactos");
        jInternalFrameFormulario.setToolTipText("");
        jInternalFrameFormulario.setVisible(true);
        jInternalFrameFormulario.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel1.setText("Correo Electronico ");
        jInternalFrameFormulario.getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel2.setText("Télefono");
        jInternalFrameFormulario.getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, -1, -1));

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel3.setText("Apellidos");
        jInternalFrameFormulario.getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, -1, -1));

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel4.setText("Nombres");
        jInternalFrameFormulario.getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, -1, -1));

        jTextNombre.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jInternalFrameFormulario.getContentPane().add(jTextNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 230, -1));

        jTextCorreo.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jInternalFrameFormulario.getContentPane().add(jTextCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 230, -1));

        jTextTelefono.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jInternalFrameFormulario.getContentPane().add(jTextTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 230, -1));

        jTextApellido.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jInternalFrameFormulario.getContentPane().add(jTextApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 230, -1));

        jButton1.setText("Agregar Contacto  ");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jInternalFrameFormulario.getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 40, -1, -1));

        jButton2.setText("Eliminar Contacto");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jInternalFrameFormulario.getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 160, 140, -1));

        jButton3.setText("Buscar Contacto");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jInternalFrameFormulario.getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 80, 140, -1));

        jButton4.setText("Modificar Contacto");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jInternalFrameFormulario.getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 120, 140, -1));

        jButton5.setText("Salir");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });
        jInternalFrameFormulario.getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 40, 130, 140));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jInternalFrameFormulario.getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 640, 270));

        getContentPane().add(jInternalFrameFormulario, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 750, 520));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OIP.jpg"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, 290, 170));

        jInternalFrame1.setTitle("Nomina Contacto");
        jInternalFrame1.setVisible(false);
        jInternalFrame1.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton6.setText("Salir");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });
        jInternalFrame1.getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 430, -1, -1));

        getContentPane().add(jInternalFrame1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 750, 530));

        jMenuContacto.setText("Contacto");

        jMenuItemFormulario.setText("Formulario Contacto");
        jMenuItemFormulario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemFormularioActionPerformed(evt);
            }
        });
        jMenuContacto.add(jMenuItemFormulario);

        jMenuItemReporte.setText("Reporte Contactos");
        jMenuItemReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemReporteActionPerformed(evt);
            }
        });
        jMenuContacto.add(jMenuItemReporte);

        jMenuBar1.add(jMenuContacto);

        jMenuSalir.setText("Salir");
        jMenuSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuSalirMouseClicked(evt);
            }
        });
        jMenuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSalirActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenuSalir);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(983, 625));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuSalirMouseClicked
        // TODO add your handling code here:
        int respuesta = JOptionPane.showConfirmDialog(this, "Seguro?", "Atencion", JOptionPane.INFORMATION_MESSAGE);
        if (respuesta==0)
            System.exit(0);
    }//GEN-LAST:event_jMenuSalirMouseClicked

    private void jMenuItemFormularioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemFormularioActionPerformed
        // TODO add your handling code here:
        jInternalFrameFormulario.setVisible(true);
        this.mostrarDatosTabla(jTable2);
        
    }//GEN-LAST:event_jMenuItemFormularioActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        Contacto contacto = new Contacto();
        ContactoADO contacto_ado = new ContactoADO();
        contacto.setCorreo(jTextCorreo.getText());
        contacto.setTelefono(jTextTelefono.getText());
        contacto.setNombre(jTextNombre.getText());
        contacto.setApellido(jTextApellido.getText());
        int rowAffected=contacto_ado.create(contacto);
        if (rowAffected==1)
            JOptionPane.showMessageDialog(this, "Contacto creado exitosamente", "Atencion", JOptionPane.INFORMATION_MESSAGE);
        else
            JOptionPane.showMessageDialog(this, "Contacto no fue creado ", "Atencion", JOptionPane.ERROR_MESSAGE);
        this.mostrarDatosTabla(jTable2);
        
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        // TODO add your handling code here:
        jTextCorreo.setText("");
        jTextTelefono.setText("");
        jTextNombre.setText("");
        jTextApellido.setText("");
        jInternalFrameFormulario.setVisible(false);
    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        ContactoADO contacto_ado = new ContactoADO();
        Contacto contacto = contacto_ado.findByEmail(jTextCorreo.getText());
        if (contacto!=null) {
            jTextCorreo.setText(contacto.getCorreo());
            jTextTelefono.setText(contacto.getTelefono());
            jTextNombre.setText(contacto.getNombre());
            jTextApellido.setText(contacto.getApellido());
            
            
        } else
            JOptionPane.showMessageDialog(this, "Contacto no existe ", "Atencion", JOptionPane.ERROR_MESSAGE);
        jTextCorreo.requestFocus();               
        
        
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        ContactoADO contacto_ado = new ContactoADO();
        Contacto contacto = contacto_ado.findByEmail(jTextCorreo.getText());
        if (contacto!=null) {
            jTextCorreo.setText(contacto.getCorreo());
            jTextTelefono.setText(contacto.getTelefono());
            jTextNombre.setText(contacto.getNombre());
            jTextApellido.setText(contacto.getApellido());
            int elimina = JOptionPane.showConfirmDialog(this, "Seguro elimina contacto?", "Atencion", JOptionPane.INFORMATION_MESSAGE);
            if (elimina==0) {
                contacto_ado.delete(contacto.getCorreo());
                jTextCorreo.setText("");
                jTextTelefono.setText("");
                jTextNombre.setText("");
                jTextApellido.setText("");
                JOptionPane.showMessageDialog(this, "Contacto eliminado exitosamente", "Atencion", JOptionPane.INFORMATION_MESSAGE);
            }
        } else
            JOptionPane.showMessageDialog(this, "Contacto no existe ", "Atencion", JOptionPane.ERROR_MESSAGE);
        jTextCorreo.requestFocus();  
        this.mostrarDatosTabla(jTable2);
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
        ContactoADO contacto_ado = new ContactoADO();
        Contacto contacto = contacto_ado.findByEmail(jTextCorreo.getText());
        if (contacto!=null) {
            contacto.setTelefono(jTextTelefono.getText());
            int rowAffected=contacto_ado.update(contacto);
            if (rowAffected==1)
                 JOptionPane.showMessageDialog(this, "Contacto actualizado exitosamente", "Atencion", JOptionPane.INFORMATION_MESSAGE);
             else
                JOptionPane.showMessageDialog(this, "Contacto no pudo actualizarse", "Atencion", JOptionPane.INFORMATION_MESSAGE);
        } else
            JOptionPane.showMessageDialog(this, "Contacto no existe ", "Atencion", JOptionPane.ERROR_MESSAGE);
        this.mostrarDatosTabla(jTable2);
    }//GEN-LAST:event_jButton4MouseClicked

    private void jMenuItemReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemReporteActionPerformed
        // TODO add your handling code here:
        jInternalFrame1.setVisible(true);
        this.mostrarDatosTabla(jTable1);
    }//GEN-LAST:event_jMenuItemReporteActionPerformed

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        // TODO add your handling code here:
        jInternalFrame1.setVisible(false);
    }//GEN-LAST:event_jButton6MouseClicked

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:
        int filaSeleccionada = jTable2.getSelectedRow();
        String correo = (String)jTable2.getValueAt(filaSeleccionada, 0);
        String telefono = (String)jTable2.getValueAt(filaSeleccionada, 1);
        String nombre = (String)jTable2.getValueAt(filaSeleccionada, 2);
        String apellido = (String)jTable2.getValueAt(filaSeleccionada, 3);
        jTextCorreo.setText(correo);
        jTextTelefono.setText(telefono);
        jTextNombre.setText(nombre);
        jTextApellido.setText(apellido);
        jTextCorreo.requestFocus();
    }//GEN-LAST:event_jTable2MouseClicked

    private void jMenuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSalirActionPerformed
               // TODO add your handling code here:
    }//GEN-LAST:event_jMenuSalirActionPerformed

    private void mostrarDatosTabla(JTable tabla) {
        Object[] titulo = {"Correo", "Telefono", "Nombre", "Apellido"};
        ContactoADO cliente_ado = new ContactoADO();
        DefaultTableModel dtm = new DefaultTableModel();
        dtm.setColumnIdentifiers(titulo);
        ArrayList<Contacto> contactos = cliente_ado.findAll();
        for (Contacto c : contactos) 
            dtm.addRow(new Object[]{c.getCorreo(), c.getTelefono(), c.getNombre(), c.getApellido()});
        tabla.setModel(dtm);
    }
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Libreta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Libreta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Libreta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Libreta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Libreta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JInternalFrame jInternalFrameFormulario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuContacto;
    private javax.swing.JMenuItem jMenuItemFormulario;
    private javax.swing.JMenuItem jMenuItemReporte;
    private javax.swing.JMenu jMenuSalir;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextApellido;
    private javax.swing.JTextField jTextCorreo;
    private javax.swing.JTextField jTextNombre;
    private javax.swing.JTextField jTextTelefono;
    // End of variables declaration//GEN-END:variables
}
