
--- PREGUNTA 1
SELECT PRO.P_CODIGO "CODIGO DEL PROYECTO",
    PRO.P_NOMBRE "NOMBRE DEL PROYECTO",
    JEFE.JP_NOMBRE || ' ' || JEFE.JP_APELLIDO_PATERNO " NOMBRE JEFE ",
    CL.C_NOMBRE  "NOMBRE CLIENTE", TI.TC_DESCRIPCION "TIPO CLIENTE",
    NVL(TO_CHAR(PRO.P_VALOR), 'NO POSEE'),
    NVL(TO_CHAR(PRO.P_VALOR * 0.15), 'NO POSEE') "VALOR DE RIESGO",
    PRO.P_FECHA_INICIO "FECHA INICIO"


FROM PROYECTO PRO JOIN JEFE_PROYECTO JEFE ON PRO.P_JEFE_RUT = JEFE.JP_RUT
    JOIN CLIENTE CL ON CL.C_RUT = PRO.P_CLIENTE_RUT
    JOIN TIPO_CLIENTE TI ON TI.TC_CODIGO = CL.C_TIPO
WHERE PRO.P_FECHA_INICIO < SYSDATE OR PRO.P_FECHA_INICIO < TO_DATE( '01/01/2010' ,'DD/MM/YYYY')
ORDER BY PRO.P_CODIGO ASC;

-- PREGUNTA 2







--PREGUNTA 4



SELECT TRA.T_NOMBRE || ' ' || TRA.T_APELLIDO_PATERNO " NOMBRE TRABAJADOR ",
    TO_CHAR(TRA.T_FECHA_NACIMIENTO, 'DD/MM/YYYY') "FECHA DE NACIMIENTO",
    TO_CHAR(TRA.T_FECHA_CONTRATO, 'DD/MM/YYYY') "FECHA CONTRATO",
    TRUNC(MONTHS_BETWEEN(SYSDATE, TRA.T_FECHA_CONTRATO) /12) "AÑOS DE TRABAJO",
    COUNT(EQ.EP_TRABAJADOR_RUT) " CANTIDAD PROYECTO"   ,
    TRUNC(MONTHS_BETWEEN(SYSDATE, TRA.T_FECHA_CONTRATO) /12)|| SUBSTR(TRA.T_APELLIDO_PATERNO, 1,3)  ||  TO_CHAR(TRA.T_FECHA_CONTRATO, 'YYYY')  || '@EMPRESA.CL' "CORREO"
FROM TRABAJADOR TRA JOIN EQUIPO_PROYECTO EQ ON EQ.EP_TRABAJADOR_RUT = TRA.T_RUT
GROUP BY TRA.T_NOMBRE, TRA.T_APELLIDO_PATERNO,TRA.T_APELLIDO_MATERNO,  TRA.T_FECHA_NACIMIENTO, TRA.T_FECHA_CONTRATO
HAVING COUNT(EQ.EP_TRABAJADOR_RUT) < 5 AND COUNT(EQ.EP_TRABAJADOR_RUT) > 2
ORDER BY TRA.T_NOMBRE|| TRA.T_APELLIDO_PATERNO || TRA.T_APELLIDO_MATERNO DESC; 

