SELECT NVL(TO_CHAR(DEPARTMENT_ID),'NO TIENE ID') "ID DEPTO",
    COUNT(EMPLOYEE_ID)"Cantida de trabajadores",
    TO_CHAR(MAX(SALARY), '999G999G999' )"Sueldo minimo", 
    TO_CHAR(MIN (SALARY), '999G999G999')"Sueldo maximo",
    TO_CHAR(TRUNC(AVG(SALARY)),'999G999G999')"Promedio de sueldos"
    FROM EMPLOYEES
    GROUP BY DEPARTMENT_ID
    ORDER BY DEPARTMENT_ID DESC;

--WHERE:


SELECT DEPARTMENT_ID "ID DEPTO",
    COUNT(EMPLOYEE_ID)"Cantida de trabajadores",
    TO_CHAR(MAX(SALARY), '999G999G999' )"Sueldo minimo", 
    TO_CHAR(MIN (SALARY), '999G999G999')"Sueldo maximo",
    TO_CHAR(TRUNC(AVG(SALARY)),'999G999G999')"Promedio de sueldos"
    FROM EMPLOYEES
    WHERE DEPARTMENT_ID IN (10,20,30)       --EN EL WHERE SIEMPRE VAN CAMPOS LIBRES (CAMPOS QUE NO TINEN FUNCIONES DE GRUPO)
    GROUP BY DEPARTMENT_ID
    ORDER BY DEPARTMENT_ID DESC;


    --HAVING:
    SELECT DEPARTMENT_ID "ID DEPTO",
    COUNT(EMPLOYEE_ID)"Cantida de trabajadores",
    TO_CHAR(MAX(SALARY), '999G999G999' )"Sueldo minimo", 
    TO_CHAR(MIN (SALARY), '999G999G999')"Sueldo maximo",
    TO_CHAR(TRUNC(AVG(SALARY)),'999G999G999')"Promedio de sueldos"
    FROM EMPLOYEES
    GROUP BY DEPARTMENT_ID  
    HAVING COUNT(EMPLOYEE_ID) > 5 --COMO EL HAVING EVALUA CONDICIONES DE FUNCIONES DE GRUPO, POR LO TANTO, EL HAVING VA DESPUES DEL GROUP BY
    ORDER BY DEPARTMENT_ID DESC;
 
 
 --WHERE Y HAVING:

 SELECT DEPARTMENT_ID "ID DEPTO",
    COUNT(EMPLOYEE_ID)"Cantida de trabajadores",
    TO_CHAR(MAX(SALARY), '999G999G999' )"Sueldo minimo", 
    TO_CHAR(MIN (SALARY), '999G999G999')"Sueldo maximo",
    TO_CHAR(TRUNC(AVG(SALARY)),'999G999G999')"Promedio de sueldos"
    FROM EMPLOYEES
    WHERE DEPARTMENT_ID IN (50,80)
    GROUP BY DEPARTMENT_ID
    HAVING COUNT(EMPLOYEE_ID) > 5
    ORDER BY DEPARTMENT_ID DESC;



--JOIN: SE USA PRA UNIR 2 TABLAS, CUANDO LA INFORMACION ESTE DISTRIBUIDA EN VARIAS TABLAS SE VA A UTILIZAR "JOIN". PARA QUE LAS TABLAS SE PUEDAN UNIR DEBEN TENER UN CAMPO EN COMUN
--DE LO CONTRARIO, NO SE PUEDEN UNIR.

SELECT DEP.DEPARTMENT_ID " DEPTO ID",
DEP.DEPARTMENT_NAME " NOMBRE DEPTO",
COUNT(EMP.EMPLOYEE_ID)"CANTIDAD TRABAJADORES"
FROM EMPLOYEES EMP
    JOIN DEPARTMENTS DEP ON EMP.DEPARTMENT_ID = DEP.DEPARTMENT_ID
GROUP BY DEP.DEPARTMENT_ID,
         DEP.DEPARTMENT_NAME
ORDER BY DEP.DEPARTMENT_ID;







