CREATE TABLE PERSONA (

 RUT VARCHAR2(15),
 NOMBRE VARCHAR2(30),
 EDAD NUMBER,
 FECHA_INGRESO DATE,
 CONSTRAINT PK_PERSONA PRIMARY KEY(RUT)
 );
 -- INSERT CON TODOS LOS VALORES
 INSERT INTO PERSONA VALUES('11.111.111-1',
                            'PERSONA 1',
                            20,
                            SYSDATE);
--INSERT CON VALORES SELECTIVOS

INSERT INTO PERSONA( RUT, NOMBRE)
                    VALUES('22.222.222-2', 'PEROSNA 2');

-- INSERT EN DESORDEN
INSERT INTO PERSONA(FECHA_INGRESO, EDAD, NOMBRE, RUT)
    VALUES(SYSDATE, 30, 'PERSONA 3', '33.333.333-3');
    
INSERT INTO PERSONA VALUES('44.444.444-4', 'PEROSNA 4', 25, SYSDATE);
INSERT INTO PERSONA VALUES('55.555.555-5', 'PEROSNA 5', 50, SYSDATE);
INSERT INTO PERSONA VALUES('66.666.666-6', 'PEROSNA 6', 60, SYSDATE);

--ESTO NO SE DEBE HACER
SELECT * --EL "*" NO SE DEBE USAR EN EL SELECT
FROM PERSONA;  --TABLA DE DONDE SE DESEA RESCATAR LA INFORMACIÓN

--ESTO SI DE DEBERIA HACER:)
SELECT RUT, NOMBRE, EDAD, FECHA_INGRESO
FROM PERSONA;

SELECT RUT "RUT TRABAJADOR", NOMBRE "NOMBRE TRABAJODR", EDAD "EDAD TRABAJODR", FECHA_INGRESO "CHUPALO"  --LAS COMILLAS DOBLES SON SOLO PARA DAR ALIAS
FROM PERSONA;
--COMO POR EJEMPLO SE PUEDE CALCULAR LA EDAD DE UN TRABAJADOR EN 5 AÑOS
SELECT EDAD"EDAD ACTUAL",  EDAD + 5"EDAD EN 5 AÑOS MÁS"
FROM PERSONA;

--FUNCION ORDER BY ESTA SIEMPRE SERÁ LA ÚLTIMA FUNCIÓN DENTRO DE UN SELECT
SELECT EDAD"EDAD ACTUAL",  EDAD + 5"EDAD EN 5 AÑOS MÁS", EDAD * 2"EDAD DOBLE"
FROM PERSONA
ORDER BY EDAD ASC;  --ASC -------> ASCENDENTE

SELECT NOMBRE"NOMBRE TRABAJADOR", EDAD"EDAD ACTUAL",  EDAD + 5"EDAD EN 5 AÑOS MÁS", EDAD * 2"EDAD DOBLE"
FROM PERSONA
ORDER BY EDAD DESC, NOMBRE ASC;  --DESC -------> DESCENDENTE

--COMO CAMBIAR DATOS DE UNA TABLA YA HECHA, UPGRADEAR
UPDATE PERSONA
SET EDAD = 99
WHERE RUT = '33.333.333-3';
-- PARA COMPROBAR QUE SE HISO EL CAMBIO
SELECT EDAD
FROM PERSONA;

--COMO AGREGAR UNA RESTRICCIÓN A UNA CONSULTA
SELECT NOMBRE "NOMBRE TRABAJADOR" , EDAD "EDAD TRABAJADOR", RUT" RUT QL"
FROM PERSONA
WHERE EDAD > 30 OR EDAD IS NULL     -- "WHERE" PERMITE INCLUIR CONDICIONES
ORDER BY EDAD ASC;








    
    
                
                

                    
                            
 
 