SELECT FIRST_NAME, LAST_NAME, SALARY
FROM employees
WHERE SALARY > 3000
ORDER BY SALARY ASC;
-- FUNCIONES DE MANIPULACIÓN DE CARACTERES:

--1.- LOWER: PERMITE TRANSFORMAR TEXTO A MINUSCULA
--EJEMPLO:
    SELECT LOWER (FIRST_NAME)
    FROM EMPLOYEES

--2.- UPPER: PERMITE TRANSFORMAR EL TEXTO A MAYUSCULA
--EJEMPLO:
    SELECT UPPER (FIRST_NAME)
    FROM EMPLOYEES
    
--3.- ||: PERMITE CONCATENAR CADENAS DE TEXTO
--EJEMPLO:
    SELECT FIRST_NAME || ' ' || LAST_NAME "Nombre completo" ,SALARY 
    FROM EMPLOYEES;

--4.- SUBSTR: PERMITE OBTENER UNA PARTE DE LA CADENA ORIGINAL
--EJEMPLO: GENERAR CORREO CORPORATIVO ASI: "FERSEP@DUOC.CL"
    SELECT SUBSTR(FIRST_NAME, 3,1 )
    FROM EMPLOYEES;
--5.- LENGTH: PERMITE OBTENER EL LARGO DE LA CADENA DE CARACTERES
--EJEMPLO:
    SELECT LENGTH('MARCO') "LONGITUD DE CARACTERES"
    FROM DUAL;
--6.-LPAD: PERMITE RELLENAR UNA CADENA DE TEXTO A LA IZQUIERDA
--EJEMPLO:
    SELECT LPAD(FIRST_NAME, 20,'*'),
                LAST_NAME
            FROM EMPLOYEES;
--7.-LPAD: PERMITE RELLENAR UNA CADENA DE TEXTO A LA DERECHA
--EJEMPLO:
    SELECT RPAD(FIRST_NAME, 20,'*'),
                LAST_NAME
            FROM EMPLOYEES;
--8.- TRIM: PERMITE QUITAR LOS ESPACIOS INNECESARIOS DE LA CADENA DE TEXTO
--EJEMPLO:
    SELECT TRIM ('   CONSULTA DE BASE DE DATOS   ') "ASIGNATURA"
    FROM DUAL;
--9.-REPLACE: PERMITE REEMPLAZAR DDENTRO DE UNA CADENA DE TEXTO
--EJEMPLO:
    SELECT REPLACE( 'ESTOY EN DUOC UC CHUPALA QL', 'U','X') "TEXTO"
    FROM DUAL;
    
    SELECT REPLACE(' PROGRAMACIÓN DE BASE DE DATOS','PROGRAMACIÓN', 'CONSULTA' ) "TEXTO"
    FROM DUAL;

            
    
-- SE PUEDEN CONBINAR LAS FUNCIONES ASI:
SELECT UPPER(LOWER(UPPER(SUBSTR(FIRST_NAME,1,3))))  --SQL LEE EL CÓDIGO DESDE ADENTRO HACIA AFUERA, OSEA, PRIMERO AGARRÓ LAS PRIMERAS 3 LETRAS, LUEGO PASO EL TEXTO A MAYUSCULA, Y ASI.
FROM EMPLOYEES;

--ASI GENERARIAMOS UN CORREO
SELECT UPPER(SUBSTR(FIRST_NAME, 1 ,3 )) ||
       UPPER(SUBSTR(FIRST_NAME, 1, 3))||
       (LENGTH (FIRST_NAME) + LENGTH(LAST_NAME))|| '@DUOC.CL' "CORREO DUOC"
       , FIRST_NAME, LAST_NAME  -- Y A MODO DE AYUDA, PONEMOS LOS NOMBRES PARA VER DE QUIENEN SON LAS INICIALES
    FROM EMPLOYEES;
    
--ASI CREA LOS CORREO DUOC
SELECT SUBSTR(FIRST_NAME, 1,1) || '.' || LAST_NAME || '@ALUMNOS.DUOC.CL' "CORREO"
FROM EMPLOYEES;


--TABLA DE AYUDA PARA PRUEBAS
SELECT UPPER(SUBSTR ('MARCO PENA' ,1,5)) "NOMBRE"
FROM DUAL;
    
--FUNCIONES DE MANUPULACIÓN DE NÚMEROS
--1.- ROUND: REDONDEAR
--EJEMPLO:
    SELECT ROUND( 3.95) "NOTA FINAL"
    FROM DUAL;
    
    SELECT ROUND( 3.966, 2) "NOTA FINAL" --ASI SE REDONDEA A 2 DECIMALES
    FROM DUAL;
    
--2.- TRUNC: TRUNCAR
--EJEMPLO:
    SELECT TRUNC( 3.95) "NOTA FINAL"
    FROM DUAL;
    
    SELECT TRUNC( 3.966, 2) "NOTA FINAL" --ASI SE TRUNCA A 2 DECIMALES
    FROM DUAL;
    
--FUNCIONES DE MANUPULACIÓN DE FECHA

--1.- TO_DATE:PERMITE TRANSFORMAR UN VARCHAR(STRING) EN U
--EJEMPLO:
    SELECT TO_DATE ('21/08/2019') --ASI NO LO RECONOCE POR QUE ESTA EN INGLES MI COMPUTADOR
    FROM DUAL;
    SELECT TO_DATE('21/08/2019' , 'DD/MM/YYYY') --ASI SE LE DA EL FORMATO QUE SE QUIERA A LA FECHA
    FROM DUAL;
--2.-MONTHS_BETWEEN: OBTTIENE LA CANTIDAD DE MESES ENTRE 2 FECHAS
--EJEMPLO:
    SELECT TRUNC (MONTHS_BETWEEN(SYSDATE, TO_DATE ('07/05/1999' , 'DD/MM/YYYY'))/12 )
    FROM DUAL;


--tarea SABER CUANTO LLEVA CONTRATADO EL EMPLEADO

SELECT FIRST_NAME, LAST_NAME, SALARY, HIRE_DATE ,TRUNC( MONTHS_BETWEEN(SYSDATE, HIRE_DATE)/12) "HIRED_DATE"
FROM EMPLOYEES
ORDER BY HIRE_DATEB DESC; 

    