SELECT * FROM EMPLOYEES;

--NOMBRE COMPLETO DE TRABAJADORES
SELECT FIRST_NAME ||' '|| LAST_NAME "NOMBRE COMPLETO"
FROM EMPLOYEES; 

--NOMBRE CON DISTINTO FORMATO-- INITCAP:PARA PONER LA PRIMERA LETRA EN MAYUSCULA
SELECT UPPER(FIRST_NAME) ||''|| INITCAP (LOWER(LAST_NAME)) "NOMBRE CON FORMATO"
FROM EMPLOYEES;

--NOMBRE Y SUELDO
SELECT UPPER (FIST_NAME) ||''|| INITCAP(LAST_NAME)"NOMBRE COMPLETO",
       SALARY "SUELDO"
FROM EMPLOYEES;

--NOMBRE Y SUELDO CON FORMATO
SELECT UPPER(FIRST_NAME)||''|| UPPER(LAST_NAME) "NOMBRE COMPLETO",
       TO_CHAR(SALARY,'999G999G999')"SUELDO CON FORMATO"
FROM EMPLOYEES;

SELECT TO_CHAR (SYSDATE, 'DD/MM/YYYY') "FECHA DEL SISTEMA",
       TO_CHAR(27800, '$9999G999') "UF DEL DIA"
FROM DUAL; 

--PARA CONVERTIR DE TEXTO A FECHA 
SELECT (MONTHS_BETWEEN(SYSDATE,TO_DATE('31/08/1987','DD/MM/YYYY'))/12)
FROM DUAL;

--EMPLEADOS DE UN DEPARTAMENTO EN PARTICULAR
SELECT FIRST_NAME||' '|| LAST_NAME "NOMBRE COMPLETO",
       SALARY "SUELDO",
       DEPARTMENT_ID "DEPARTAMENTO"
FROM EMPLOYEES 
WHERE DEPARTMENT_ID=30 OR DEPARTMENT_ID=40
ORDER BY DEPARTMENT_ID;

--EJEMPLO ANTERIOR MEJORADO  IN: DENTRO DE / NOT IN: NO DENTRO DE 
SELECT FIRST_NAME ||' '|| LAST_NAME "NOMBRE COMPLETO",
       SALARY "SUELDO",
       DEPARTMENT_ID "DEPARTAMENTO"
FROM EMPLOYEES 
WHERE DEPARTMENT_ID IN (30,40,50)
ORDER BY DEPARTMENT_ID;

--OBTENER TRABAJADORES QUE GANAN MAS DE 5K  NVL: PARA CAMBIAR UN DATO QUE ES NULO
SELECT FIRST_NAME ||' '|| LAST_NAME "NOMBRE COMPLETO",
       SALARY "SUELDO",
       NVL(TO_CHAR(DEPARTMENT_ID),'NO POSEE DEPTO') "DEPARTAMENTO" --SE USA TO_CHAR PARA PONER UN TEXTO UWU
FROM EMPLOYEES
WHERE SALARY > 5000 --AND DEPARTMENT_ID IS NOT NULL---> PARA CUANDO SALGA VALORES NULOS NO LOS MUESTRE
ORDER BY SALARY;

--EXPLICACION PARA NVL 
SELECT DEPARTMENT_ID "DEPTO ID",
       DEPARTMENT_NAME "DEPTO NOMBRE",
       NVL(MANAGER_ID, 9999999) "JEFE", --TAMBIEN PUEDE SER: NVL(TO_CHAR(MANAGER_ID), 'NO POSEE JEFE') "JEFE",
       LOCATION_ID "UBICACION"
FROM DEPARTMENTS;

SELECT NVL(NULL, 'NO POSEE') "SALIDA"
FROM DUAL;

--CREACION DE CORREO--   
SELECT UPPER(FIRST_NAME)||' '|| UPPER(LAST_NAME) "NOMBRE COMPLETO",
       TO_CHAR(SALARY,'999G999G999') "SUELDO",
       UPPER(SUBSTR(FIRST_NAME, 1, 3)||SUBSTR(LAST_NAME,1, 2)) 
       ||LENGTH(FIRST_NAME)|| '@DUOC.CL' "CORREO",
       SUBSTR(FIRST_NAME,1, 1) "PRIMERA LETRA DEL NOMBRE",
       CASE SUBSTR(FIRST_NAME,1, 1) -- ES COMO USAR UN IF
       WHEN 'A' THEN 'COMUNA A'
       WHEN 'B' THEN 'COMUNA B'
       ELSE 'OTRA COMUNA'
       END "COMUNA"
FROM EMPLOYEES
ORDER BY FIRST_NAME;

--VARIACION DE CASE
SELECT UPPER(FIRST_NAME)||' '|| UPPER(LAST_NAME) "NOMBRE COMPLETO",
       TO_CHAR(SALARY,'999G999G999') "SUELDO",
       UPPER(SUBSTR(FIRST_NAME, 1, 3)||SUBSTR(LAST_NAME,1, 2)) 
       ||LENGTH(FIRST_NAME)|| '@DUOC.CL' "CORREO",
       SUBSTR(FIRST_NAME,1, 1) "PRIMERA LETRA DEL NOMBRE",
       CASE 
       WHEN SUBSTR(FIRST_NAME,1,1) BETWEEN 'A' AND 'E' THEN 'PRIMERA COMUNA'
       WHEN SUBSTR(FIRST_NAME,1,1) BETWEEN 'F' AND 'R' THEN 'PRIMERA COMUNA'
       WHEN SUBSTR(FIRST_NAME,1,1) BETWEEN 'S' AND 'Z' THEN 'PRIMERA COMUNA'
       END "COMUNA"
FROM EMPLOYEES
ORDER BY FIRST_NAME;

--CLASIFICACION DE PERSDONAS SEGUN SUELDO
SELECT FIRST_NAME||' '|| LAST_NAME "NOMBRE COMPLETO",
       SALARY "SUELDO",
       CASE
       WHEN SALARY BETWEEN 1000 AND 3000 THEN 'CLASE C'
       WHEN SALARY BETWEEN 3001 AND 5000 THEN 'CLASE B'
       WHEN SALARY >= 5001 THEN 'CLASE A'
       END "CLASIFICACION"
FROM EMPLOYEES
ORDER BY SALARY ASC;

--AUMENTO DE SUELDO SEGUN SUELDO

SELECT FIRST_NAME||' '|| LAST_NAME "NOMBRE COMPLETO",
       SALARY "SUELDO",
       TO_CHAR(ROUND(CASE 
       WHEN SALARY > 10000 THEN SUBSTR(SALARY,1,2)*SALARY/100 ---UPDATE tabla SET precio = ROUND( precio * 1.20, 2 )
       WHEN SALARY < 10000 THEN SUBSTR(SALARY,1,1)*SALARY/100
       END), '9999G999G999') "AUMENTO",
       TO_CHAR(ROUND(SALARY + CASE --DE AQUI PARA ABAJO ES PARA SUMAR Y SABER CUANTO AUMENTO EL SUELDO
       WHEN SALARY > 10000 THEN SUBSTR(SALARY,1,2)*SALARY/100
       WHEN SALARY < 10000 THEN SUBSTR(SALARY,1,1)*SALARY/100
       END), '999G999G999') "SUELDO AUMENTADO"
FROM EMPLOYEES;

--BONO SEGUN FECHA DE CONTRATO 
SELECT FIRST_NAME||' '|| LAST_NAME "NOMBRE COMPLETO",
       TO_CHAR(SALARY, '999G999G999') "SUELDO",
       TO_CHAR(HIRE_DATE, 'DD/MM/YYYY') "FECHA DE CONTRATO",
       TO_CHAR(HIRE_DATE, 'DD') ||' DE '|| TRIM(TO_CHAR(HIRE_DATE, 'MONTH'))--PRUEBA CON SACAR EL TRIM Y LOS PARENTESIS PARA VER LA DIFERENCIA
       ||' DE '|| TO_CHAR(HIRE_DATE,'YYYY')"FECHA CON FORMATO"
FROM EMPLOYEES;


