---PREGUNTA 1:
SELECT A_RUT "RUT ALUMNO" ,
       A_NOMBRES || ' ' || A_APELLIDO_PATERNO || ' '|| A_APELLIDO_MATERNO  "NOMBRE COMPLETO",
       A_TIPO_ALUMNO "TIPO ALUMNO"
       
FROM ALUMNO
WHERE A_TIPO_ALUMNO != 'TA01';
