

SELECT DEP.DEPARTMENT_NAME "DEPARTMENT NAME",
    COUNT(EMP.EMPLOYEE_ID)"EMPLOYEES"
FROM DEPARTMENTS DEP LEFT JOIN EMPLOYEES EMP ON DEP.DEPARTMENT_ID = EMP.DEPARTMENT_ID --PARA QUE EL JOIN UNA TABLA LAS CONDICIONES DEBEN CUMPLIRSE
GROUP BY DEP.DEPARTMENT_NAME
ORDER BY COUNT (EMP.EMPLOYEE_ID);
-- EL LEFT JOIN : VA A TRAER LO QUE ESTA A LA IZQUIERDA ADEMAS DE LO QUE ESTA EN LA DERECHA
SELECT *
FROM DEPARTMENTS; 

SELECT DEP.DEPARTMENT_NAME "NAME EMPLOYEE",
    COUNT(EMP.EMPLOYEE_ID)"EMPLOYEES"
FROM EMPLOYEES EMP RIGHT JOIN DEPARTMENTS DEP ON DEP.DEPARTMENT_ID = EMP.DEPARTMENT_ID --PARA QUE EL JOIN UNA TABLA LAS CONDICIONES DEBEN CUMPLIRSE
GROUP BY DEP.DEPARTMENT_NAME
ORDER BY COUNT (EMP.EMPLOYEE_ID);

--EL RIGHT JOIN : VA A TRAER LO QUE ESTA A LA DERECHA ADEMAS DE LO QUE ESTA EN LA IZQUIERDA

SELECT DEP.DEPARTMENT_NAME "NAME EMPLOYEE",
    COUNT(EMP.EMPLOYEE_ID)"EMPLOYEES"
FROM EMPLOYEES EMP FULL JOIN DEPARTMENTS DEP ON DEP.DEPARTMENT_ID = EMP.DEPARTMENT_ID --PARA QUE EL JOIN UNA TABLA LAS CONDICIONES DEBEN CUMPLIRSE
GROUP BY DEP.DEPARTMENT_NAME
ORDER BY COUNT (EMP.EMPLOYEE_ID);

--FULL JOIN: ESTO ATRAERA TODO LO QUE ESTA EN LAS 2 TABLAS ADEMAS DE LA INTERCEPCION
 

--OUTER JOIN: ERA NESESARIO PARA MOTORES ANTIGUOS, YA NO SE USA.


------------------------------------------------------------------------------------------------------------------------------------------------------------

--SUBCONSULTAS : UNA CONSULTA DENTRO DE UNA CONSULTA

--TIPICA PREGUNTA DE PRUEBA, SE NECESITA TRAER A TODOS LOS EMPLEADOS QUE GANAN MAS QUE TODO EL PROMEDIO

SELECT FIRST_NAME || ' ' || LAST_NAME " NOMBRE COMPLETO",
    SALARY "SALARIO",
    DEPARTMENT_ID " DEPTO ID"

FROM EMPLOYEES
WHERE SALARY >= 6462;

SELECT ROUND(AVG(SALARY))
FROM EMPLOYEES;
--HACER TODO LO ANTERIOR ESTA MAL POR QUE SI HAY ALGUN CAMBIO EN LA TABLA DE EMPLOYEES, SI SE DESPIDE O SE CONTRATA UN TRABAJADOR, EL PROMEDIO CAMBIARA

--ESTO SE HACE:

SELECT FIRST_NAME || ' ' || LAST_NAME " NOMBRE COMPLETO",
    SALARY "SALARIO",
    DEPARTMENT_ID " DEPTO ID"
FROM EMPLOYEES
WHERE SALARY >= (SELECT ROUND(AVG(SALARY))
                FROM EMPLOYEES);
--CON HACER LO ANTERIOR TENDREMOS SIEMPRE ACTUALIZADO EL PROMEDIO DE LA TABLA DE TRABAJADORES


--CUANDO USAMOS UNA SUBCONSULTA ES PARA BUSCAR UN VALOR QUE NO CONOSCAMOS



--SE NECESITA OBTENER UN REPORTE DE LOS DEPARTAMENTOS CON SU CANTIDAD DE TRABAJADORES SOLAMENTES DE AQUELLOS QUE POSSEEN MAS EMPLEADOS QUE EL DEPARTAMENTO EXECUTIVE


SELECT DEP.DEPARTMENT_NAME "DEPARTMENT NAME",
    COUNT(EMP.EMPLOYEE_ID)"EMPLOYEES"
FROM DEPARTMENTS DEP LEFT JOIN EMPLOYEES EMP ON DEP.DEPARTMENT_ID = EMP.DEPARTMENT_ID --PARA QUE EL JOIN UNA TABLA LAS CONDICIONES DEBEN CUMPLIRSE
GROUP BY DEP.DEPARTMENT_NAME
HAVING COUNT(EMP.EMPLOYEE_ID) > (SELECT COUNT(EMP.EMPLOYEE_ID) FROM DEPARTMENTS DEP JOIN EMPLOYEES EMP ON DEP.DEPARTMENT_ID = EMP .DEPARTMENT_ID
                                    WHERE DEP.DEPARTMENT_NAME = 'Executive')
ORDER BY COUNT (EMP.EMPLOYEE_ID);

--decimas

SELECT FIRST_NAME || ' ' || LAST_NAME " NOMBRE COMPLETO", 'DEPTO 30' "TIPO" 
FROM EMPLOYEES
WHERE DEPARTMENT_ID = 30
UNION -- ESTO UNO LAS DOS CONSULTAS, NO IMPORTA QUE NO HALLAN CAMPOS QUE SE REFIERAN A LO MISMO
SELECT DEPARTMENT_NAME, 'DEPARTAMENTO' FROM DEPARTMENTS
ORDER BY 2;

--REPORTE QUE TRAIGA LOS DEPTOS DE LA CANTIDAD DE TRABAJADORES SOLO  DE AQUELLOS QUE TENGAN MAS TRABAJADORES QUE EL PROMEDIO


SELECT DEP.DEPARTMENT_NAME "DEPARTMENT NAME",
    COUNT(EMP.EMPLOYEE_ID)"EMPLOYEES"
FROM DEPARTMENTS DEP JOIN EMPLOYEES EMP ON DEP.DEPARTMENT_ID = EMP.DEPARTMENT_ID --PARA QUE EL JOIN UNA TABLA LAS CONDICIONES DEBEN CUMPLIRSE
GROUP BY DEP.DEPARTMENT_NAME
HAVING COUNT(EMP.EMPLOYEE_ID)> (SELECT AVG(COUNT(EMP.EMPLOYEE_ID))"EMPLOYEES"
                                    FROM DEPARTMENTS DEP LEFT JOIN EMPLOYEES EMP ON DEP.DEPARTMENT_ID = EMP.DEPARTMENT_ID --PARA QUE EL JOIN UNA TABLA LAS CONDICIONES DEBEN CUMPLIRSE
                                            GROUP BY DEP.DEPARTMENT_NAME)

ORDER BY COUNT (EMP.EMPLOYEE_ID);



----------------------------------------------------
CREATE TABLE DEPTO_RESPALDO AS
SELECT *
FROM DEPARTMENTS
WHERE DEPARTMENT_ID = 30;


SELECT * 
FROM DEPTO_RESPALDO
DROP TABLE DEPTO_RESPALDO

DELETE FROM DEPTO_RESPALDO;

