--2:
SELECT * 
FROM EDIFICIO;

SELECT * 
FROM DEPARTAMENTO;



SELECT  ED.EDI_NOMBRE_EDIFICIO "NOMBRE EDIFICIO",
       COM.NOMBRE_COMUNA "NOMBRE COMUNA",
       TO_CHAR(ADM.ADM_NUMRUN,'99G999G999')||'-'||ADM.ADM_DVRUN "RUN ADMINISTRADOR",
       ADM.ADM_PNOMBRE||' ' || ADM.ADM_SNOMBRE||' '|| ADM.ADM_APELLIDO_PATERNO||' '||ADM.ADM_APELLIDO_MATERNO "NOMBRE  ADMINISTRADOR",
       COUNT(DEP.ID_EDIFICIO) "TOTAL DEPARTAMENTOS"
    
FROM EDIFICIO ED
JOIN DEPARTAMENTO DEP ON ED.ID_EDIFICIO = DEP.ID_EDIFICIO 
JOIN ADMINISTRADOR ADM ON ADM.ADM_NUMRUN = ED.ADM_NUMRUN
JOIN COMUNA COM ON ED.ID_COMUNA =  COM.ID_COMUNA
JOIN GASTO_COMUN CMGAS ON DEP.ID_EDIFICIO = CMGAS.ID_EDIFICIO AND DEP.NRO_DEPARTAMENTO = CMGAS.NRO_DEPARTAMENTO
JOIN PAGO_GASTO_COMUN PGC ON DEP.ID_EDIFICIO = PGC.ID_EDIFICIO AND CMGAS.NRO_DEPARTAMENTO = PGC.NRO_DEPARTAMENTO AND CMGAS.PCO_PERIODO = PGC.PCO_PERIODO

GROUP BY DEP.ID_EDIFICIO, ED.EDI_NOMBRE_EDIFICIO, NOMBRE_COMUNA, TO_CHAR(ADM.ADM_NUMRUN,'99G999G999')||'-'||ADM.ADM_DVRUN, ADM.ADM_PNOMBRE||' ' || ADM.ADM_SNOMBRE||' '|| ADM.ADM_APELLIDO_PATERNO||' '||ADM.ADM_APELLIDO_MATERNO
ORDER BY COM.NOMBRE_COMUNA ASC;


SElECT COUNT(NRO_DEPARTAMENTO),
ID_EDIFICIO
FROM DEPARTAMENTO
GROUP BY ID_EDIFICIO;





--3

SELECT ED.EDI_NOMBRE_EDIFICIO "NOMBRE EDIFICIO",


FROM EDIFICIO ED;



