package vista;

import controlador.AccesToBDUsers;
import controlador.BDTableGastos;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import modelo.TipoPago;
import modelo.User;

/**
 *
 * @author marco
 */
public class Jarvis extends javax.swing.JFrame {

    private String secretKey = "Kakaroto";

    /**
     * Creates new form Jarvis
     */
    public Jarvis() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrameLoginIN = new javax.swing.JInternalFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableVentas = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanelPrincipal = new javax.swing.JPanel();
        jButtonLogin1 = new javax.swing.JButton();
        jButtonLogin = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();
        jInternalFrameLogin = new javax.swing.JInternalFrame();
        jPanelLogin = new javax.swing.JPanel();
        jButtonLoginLogin = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPasswordFieldContrasenia = new javax.swing.JPasswordField();
        jTextFieldUsuario = new javax.swing.JTextField();
        jButtonSalir2 = new javax.swing.JButton();
        rSLabelHora1 = new rojeru_san.RSLabelHora();
        rSLabelFecha1 = new rojeru_san.RSLabelFecha();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jInternalFrameSignUp = new javax.swing.JInternalFrame();
        jPanelSignUp = new javax.swing.JPanel();
        jLabelUser = new javax.swing.JLabel();
        jLabelUser1 = new javax.swing.JLabel();
        jTextFieldUserSignUp = new javax.swing.JTextField();
        jPasswordFieldConfirmPassword = new javax.swing.JPasswordField();
        jButton3 = new javax.swing.JButton();
        jLabelUser2 = new javax.swing.JLabel();
        jPasswordFieldPasswordSignUp = new javax.swing.JPasswordField();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Jarvis 1.0");
        setBackground(Color.magenta);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setResizable(false);

        jInternalFrameLoginIN.setForeground(new java.awt.Color(0, 0, 0));
        jInternalFrameLoginIN.setMinimumSize(new java.awt.Dimension(800, 600));
        jInternalFrameLoginIN.setPreferredSize(new java.awt.Dimension(800, 600));
        jInternalFrameLoginIN.setRequestFocusEnabled(false);
        try {
            jInternalFrameLoginIN.setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }
        jInternalFrameLoginIN.setVisible(false);
        jInternalFrameLoginIN.getContentPane().setLayout(null);

        jTableVentas.setBackground(new java.awt.Color(255, 0, 255));
        jTableVentas.setBorder(new javax.swing.border.MatteBorder(new javax.swing.ImageIcon(getClass().getResource("/imagenes/thumb-1920-888539.png")))); // NOI18N
        jTableVentas.setFont(new java.awt.Font("Lucida Console", 1, 12)); // NOI18N
        jTableVentas.setForeground(new java.awt.Color(255, 255, 255));
        jTableVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "FECHA", "MÉTODO DE PAGO", "GASTO", "NOTAS"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableVentas.setToolTipText("");
        jTableVentas.setFocusable(false);
        jTableVentas.setGridColor(new java.awt.Color(0, 0, 0));
        jTableVentas.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTableVentas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableVentasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableVentas);

        jInternalFrameLoginIN.getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(220, 120, 690, 140);

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setText("Cerrar Sesión");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jInternalFrameLoginIN.getContentPane().add(jButton2);
        jButton2.setBounds(1130, 530, 110, 32);

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setForeground(Color.BLACK);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/913734.jpg"))); // NOI18N
        jInternalFrameLoginIN.getContentPane().add(jLabel2);
        jLabel2.setBounds(-2470, -200, 4330, 1730);

        getContentPane().add(jInternalFrameLoginIN, java.awt.BorderLayout.PAGE_START);

        jPanelPrincipal.setBackground(new java.awt.Color(204, 0, 102));
        jPanelPrincipal.setMinimumSize(new java.awt.Dimension(1280, 720));
        jPanelPrincipal.setPreferredSize(new java.awt.Dimension(1280, 720));
        jPanelPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonLogin1.setBackground(new java.awt.Color(0, 0, 0));
        jButtonLogin1.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        jButtonLogin1.setForeground(new java.awt.Color(255, 0, 0));
        jButtonLogin1.setText("Login");
        jButtonLogin1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonLogin1MouseClicked(evt);
            }
        });
        jPanelPrincipal.add(jButtonLogin1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 430, 140, 100));

        jButtonLogin.setBackground(new java.awt.Color(0, 0, 0));
        jButtonLogin.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        jButtonLogin.setForeground(new java.awt.Color(255, 0, 0));
        jButtonLogin.setText("Sign Up");
        jButtonLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonLoginMouseClicked(evt);
            }
        });
        jPanelPrincipal.add(jButtonLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 430, 140, 100));

        jButtonSalir.setBackground(new java.awt.Color(0, 0, 0));
        jButtonSalir.setForeground(new java.awt.Color(255, 0, 0));
        jButtonSalir.setText("Salir");
        jButtonSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonSalirMouseClicked(evt);
            }
        });
        jPanelPrincipal.add(jButtonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 640, 80, 40));

        jInternalFrameLogin.setBackground(new java.awt.Color(0, 0, 0));
        jInternalFrameLogin.setForeground(new java.awt.Color(0, 0, 0));
        jInternalFrameLogin.setTitle("Login");
        jInternalFrameLogin.setToolTipText("");
        jInternalFrameLogin.setPreferredSize(new java.awt.Dimension(600, 400));
        jInternalFrameLogin.setVisible(false);
        jInternalFrameLogin.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelLogin.setBackground(Color.red);
        jPanelLogin.setLayout(null);

        jButtonLoginLogin.setBackground(new java.awt.Color(0, 0, 0));
        jButtonLoginLogin.setForeground(new java.awt.Color(255, 0, 0));
        jButtonLoginLogin.setText("Login");
        jButtonLoginLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonLoginLoginMouseClicked(evt);
            }
        });
        jPanelLogin.add(jButtonLoginLogin);
        jButtonLoginLogin.setBounds(470, 180, 61, 32);

        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Password");
        jPanelLogin.add(jLabel1);
        jLabel1.setBounds(40, 170, 58, 16);

        jPasswordFieldContrasenia.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jPasswordFieldContrasenia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldContraseniaActionPerformed(evt);
            }
        });
        jPasswordFieldContrasenia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordFieldContraseniaKeyPressed(evt);
            }
        });
        jPanelLogin.add(jPasswordFieldContrasenia);
        jPasswordFieldContrasenia.setBounds(30, 200, 240, 30);
        jPanelLogin.add(jTextFieldUsuario);
        jTextFieldUsuario.setBounds(30, 80, 240, 30);

        jButtonSalir2.setBackground(new java.awt.Color(0, 0, 0));
        jButtonSalir2.setForeground(new java.awt.Color(255, 0, 0));
        jButtonSalir2.setText("Exit");
        jButtonSalir2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonSalir2MouseClicked(evt);
            }
        });
        jPanelLogin.add(jButtonSalir2);
        jButtonSalir2.setBounds(470, 230, 60, 32);

        rSLabelHora1.setForeground(new java.awt.Color(0, 0, 0));
        jPanelLogin.add(rSLabelHora1);
        rSLabelHora1.setBounds(460, 80, 110, 30);

        rSLabelFecha1.setForeground(new java.awt.Color(0, 0, 0));
        jPanelLogin.add(rSLabelFecha1);
        rSLabelFecha1.setBounds(460, 20, 110, 30);

        jLabel8.setBackground(new java.awt.Color(255, 0, 0));
        jLabel8.setForeground(new java.awt.Color(255, 0, 0));
        jLabel8.setText("User");
        jPanelLogin.add(jLabel8);
        jLabel8.setBounds(40, 50, 41, 16);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/thumb-1920-888539.png"))); // NOI18N
        jPanelLogin.add(jLabel3);
        jLabel3.setBounds(-480, 0, 1080, 690);

        jInternalFrameLogin.getContentPane().add(jPanelLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 300));

        jPanelPrincipal.add(jInternalFrameLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 320));

        jButton1.setText("ingresar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jPanelPrincipal.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 110, -1, -1));
        jPanelPrincipal.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 40, 290, -1));

        jInternalFrameSignUp.setTitle("Sign Up");
        jInternalFrameSignUp.setVisible(false);

        jPanelSignUp.setBackground(new java.awt.Color(204, 204, 255));

        jLabelUser.setForeground(new java.awt.Color(0, 0, 0));
        jLabelUser.setText("User");

        jLabelUser1.setForeground(new java.awt.Color(0, 0, 0));
        jLabelUser1.setText("Password");

        jTextFieldUserSignUp.setText(" ");

        jButton3.setText("Exit");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jButton3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton3KeyPressed(evt);
            }
        });

        jLabelUser2.setForeground(new java.awt.Color(0, 0, 0));
        jLabelUser2.setText("Confirm Password");

        jButton4.setText("Sign Up");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelSignUpLayout = new javax.swing.GroupLayout(jPanelSignUp);
        jPanelSignUp.setLayout(jPanelSignUpLayout);
        jPanelSignUpLayout.setHorizontalGroup(
            jPanelSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSignUpLayout.createSequentialGroup()
                .addGroup(jPanelSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelSignUpLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jPanelSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelUser2)
                            .addComponent(jLabelUser1)))
                    .addGroup(jPanelSignUpLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabelUser)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addGroup(jPanelSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPasswordFieldPasswordSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelSignUpLayout.createSequentialGroup()
                        .addComponent(jTextFieldUserSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addGroup(jPanelSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton4)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPasswordFieldConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
        );
        jPanelSignUpLayout.setVerticalGroup(
            jPanelSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSignUpLayout.createSequentialGroup()
                .addGroup(jPanelSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelSignUpLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(jPanelSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelUser)
                            .addComponent(jTextFieldUserSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelSignUpLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jButton4)))
                .addGap(45, 45, 45)
                .addGroup(jPanelSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPasswordFieldPasswordSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelUser1))
                .addGroup(jPanelSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelSignUpLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(jPanelSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelUser2)
                            .addComponent(jPasswordFieldConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSignUpLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                        .addComponent(jButton3)
                        .addGap(68, 68, 68))))
        );

        javax.swing.GroupLayout jInternalFrameSignUpLayout = new javax.swing.GroupLayout(jInternalFrameSignUp.getContentPane());
        jInternalFrameSignUp.getContentPane().setLayout(jInternalFrameSignUpLayout);
        jInternalFrameSignUpLayout.setHorizontalGroup(
            jInternalFrameSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelSignUp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jInternalFrameSignUpLayout.setVerticalGroup(
            jInternalFrameSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelSignUp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanelPrincipal.add(jInternalFrameSignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 480, 270));

        getContentPane().add(jPanelPrincipal, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSalirMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jButtonSalirMouseClicked

    private void jButtonLogin1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonLogin1MouseClicked

        jInternalFrameLogin.setVisible(true);

    }//GEN-LAST:event_jButtonLogin1MouseClicked

    private void jButtonLoginLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonLoginLoginMouseClicked
        AccesToBDUsers bd = new AccesToBDUsers();

        String Pass = new String(jPasswordFieldContrasenia.getPassword());
        String iPass = bd.ecnode(secretKey, Pass);
        String user = jTextFieldUsuario.getText();
        int acces = bd.Login(user, iPass);
        if (acces == 1) {
            JOptionPane.showMessageDialog(this, "Seción iniciada correctamente", "atención", JOptionPane.INFORMATION_MESSAGE);
            jInternalFrameLoginIN.setVisible(true);
            jInternalFrameLogin.setVisible(false);
            this.mostrarTabla(jTableVentas);
        } else {
            JOptionPane.showMessageDialog(this, "Usuario y/o contraseña incorrecta", "atención", JOptionPane.INFORMATION_MESSAGE);
        }


    }//GEN-LAST:event_jButtonLoginLoginMouseClicked

    private void jButtonSalir2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSalir2MouseClicked
        jInternalFrameLogin.setVisible(false);          // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSalir2MouseClicked

    private void jPasswordFieldContraseniaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordFieldContraseniaKeyPressed
        int key = evt.getKeyChar();
        System.out.println(key);
        if (key == 10) {
            AccesToBDUsers bd = new AccesToBDUsers();

            String Pass = new String(jPasswordFieldContrasenia.getPassword());
            String iPass = bd.ecnode(secretKey, Pass);
            String user = jTextFieldUsuario.getText();
            int acces = bd.Login(user, iPass);
            if (acces == 1) {
                JOptionPane.showMessageDialog(this, "Seción iniciada correctamente", "atención", JOptionPane.INFORMATION_MESSAGE);
                jInternalFrameLogin.setVisible(false);
                jInternalFrameLoginIN.setVisible(true);
                this.mostrarTabla(jTableVentas);
            } else {
                JOptionPane.showMessageDialog(this, "Usuario y/o contraseña incorrecta", "atención", JOptionPane.INFORMATION_MESSAGE);
            }

        }


    }//GEN-LAST:event_jPasswordFieldContraseniaKeyPressed

    private void jPasswordFieldContraseniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldContraseniaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordFieldContraseniaActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        String fecha = ((JTextField) jDateChooser1.getDateEditor().getUiComponent()).getText();
        BDTableGastos bd = new BDTableGastos();
        int row = bd.addGasto(987654321, fecha, "TBK", 20000, "Compra Santa Isabel");
        if (row == 1) {
            JOptionPane.showMessageDialog(this, "Atencion", "HOla", JOptionPane.INFORMATION_MESSAGE);
        } else {
            System.out.println("no");
        }

    }//GEN-LAST:event_jButton1MouseClicked

    private void jTableVentasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableVentasMouseClicked
        this.mostrarTabla(jTableVentas);        // TODO add your handling code here:
    }//GEN-LAST:event_jTableVentasMouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked

        int salir = JOptionPane.showConfirmDialog(this, "Seguro que quiere cerrar la sesión?", "Atención", JOptionPane.YES_NO_OPTION);
        if (salir == 0) {
            jInternalFrameLoginIN.setVisible(false);
        }

    }//GEN-LAST:event_jButton2MouseClicked

    private void jButtonLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonLoginMouseClicked
        jInternalFrameSignUp.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonLoginMouseClicked

    private void jButton3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton3KeyPressed

    }//GEN-LAST:event_jButton3KeyPressed

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        jInternalFrameSignUp.setVisible(false); // TODO add your handling code here:
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        AccesToBDUsers bd = new AccesToBDUsers();
        String user = jTextFieldUserSignUp.getText();
        String password = new String(jPasswordFieldPasswordSignUp.getPassword());
        String confirmPassword = new String(jPasswordFieldConfirmPassword.getPassword());
        String incriptedPassword = bd.ecnode(secretKey, confirmPassword);
        int code = (int) (Math.random() * 100000000 + 1);
        User u = new User(code, user, incriptedPassword);
        if (password.equals(confirmPassword)) {
            bd.addUser(u);
            JOptionPane.showMessageDialog(this, "Usuario creado correctamente", "Atención",JOptionPane.WARNING_MESSAGE);
            jTextFieldUserSignUp.setText("");
            jPasswordFieldPasswordSignUp.setText("");
            jPasswordFieldConfirmPassword.setText("");
            jInternalFrameSignUp.setVisible(false);

        }else{
            JOptionPane.showMessageDialog(this, "Las contraseña no coninciden", "Atención",JOptionPane.WARNING_MESSAGE);
        }
        


    }//GEN-LAST:event_jButton4MouseClicked

    private void mostrarTabla(JTable tabla) {

        Object[] titulo = {"FECHA", "MÉTODO DE PAGO", "GASTO", "NOTAS"};
        BDTableGastos bd = new BDTableGastos();
        TipoPago pago = new TipoPago();
        DefaultTableModel dfm = new DefaultTableModel();
        dfm.setColumnIdentifiers(titulo);
        ArrayList<TipoPago> pagos = bd.searchAll();
        for (TipoPago p : pagos) {
            dfm.addRow(new Object[]{p.getFecha(), p.getMetodoPago(), p.getGasto(), p.getNotas()});
        }

        tabla.setModel(dfm);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Jarvis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Jarvis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Jarvis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Jarvis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Jarvis().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButtonLogin;
    private javax.swing.JButton jButtonLogin1;
    private javax.swing.JButton jButtonLoginLogin;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JButton jButtonSalir2;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JInternalFrame jInternalFrameLogin;
    private javax.swing.JInternalFrame jInternalFrameLoginIN;
    private javax.swing.JInternalFrame jInternalFrameSignUp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelUser;
    private javax.swing.JLabel jLabelUser1;
    private javax.swing.JLabel jLabelUser2;
    private javax.swing.JPanel jPanelLogin;
    private javax.swing.JPanel jPanelPrincipal;
    private javax.swing.JPanel jPanelSignUp;
    private javax.swing.JPasswordField jPasswordFieldConfirmPassword;
    private javax.swing.JPasswordField jPasswordFieldContrasenia;
    private javax.swing.JPasswordField jPasswordFieldPasswordSignUp;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableVentas;
    private javax.swing.JTextField jTextFieldUserSignUp;
    private javax.swing.JTextField jTextFieldUsuario;
    private rojeru_san.RSLabelFecha rSLabelFecha1;
    private rojeru_san.RSLabelHora rSLabelHora1;
    // End of variables declaration//GEN-END:variables
}
