//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnBrakeDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Respaldo
    {
        public float Id { get; set; }
        public string RazonSocial { get; set; }
        public string fecha_inicio { get; set; }
        public string hora_inicio { get; set; }
        public string evento_realizado { get; set; }
        public string Tipo_evento { get; set; }
        public string Modalidad_evento { get; set; }
        public string Tipo_ambientacion { get; set; }
        public string Musica_ambiental { get; set; }
        public string Musica_cliente { get; set; }
        public string Fecha_termino { get; set; }
        public string local_o { get; set; }
        public string Hora_termino { get; set; }
        public string Observaciones { get; set; }
        public string Asistentes_evento { get; set; }
        public string Personal_adicional { get; set; }
        public string Valor_contrato { get; set; }
    }
}
