//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADO.Conn
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLEADO
    {
        public int IDEMPLEADO { get; set; }
        public string NOMBRES { get; set; }
        public string APELLIDOS { get; set; }
        public string RUT { get; set; }
        public string ESTADO_CIVIL { get; set; }
    }
}
