package vista;


import controlador.Registro;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import modelo.Paciente;


/**
 *
 * @author Nicolas Garces, Marco Peña
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jInternalFrameAgregar = new javax.swing.JInternalFrame();
        jLabelRut = new javax.swing.JLabel();
        jTextFieldRut = new javax.swing.JTextField();
        jLabelNombre = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jLabelGenero = new javax.swing.JLabel();
        jRadioButtonMasculino = new javax.swing.JRadioButton();
        jRadioButtonFemenino1 = new javax.swing.JRadioButton();
        jLabelEdad = new javax.swing.JLabel();
        jTextFieldEdad = new javax.swing.JTextField();
        jLabelDireccion = new javax.swing.JLabel();
        jTextFieldDireccion = new javax.swing.JTextField();
        jLabelCiudad = new javax.swing.JLabel();
        jComboBoxCiudad = new javax.swing.JComboBox<>();
        jLabelIsapre = new javax.swing.JLabel();
        jRadioButtonSi = new javax.swing.JRadioButton();
        jRadioButtonNo = new javax.swing.JRadioButton();
        jLabelDonante = new javax.swing.JLabel();
        jCheckBoxDondante = new javax.swing.JCheckBox();
        jButtonLimpiar = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();
        jButtonGuardar = new javax.swing.JButton();
        jInternalFrameModificar = new javax.swing.JInternalFrame();
        jLabelRut1 = new javax.swing.JLabel();
        jTextFieldRut1 = new javax.swing.JTextField();
        jLabelNombre1 = new javax.swing.JLabel();
        jTextFieldNombre1 = new javax.swing.JTextField();
        jLabelGenero1 = new javax.swing.JLabel();
        jRadioButtonMasculino1 = new javax.swing.JRadioButton();
        jRadioButtonFemenino2 = new javax.swing.JRadioButton();
        jLabelEdad1 = new javax.swing.JLabel();
        jTextFieldEdad1 = new javax.swing.JTextField();
        jLabelDireccion1 = new javax.swing.JLabel();
        jTextFieldDireccion1 = new javax.swing.JTextField();
        jLabelCiudad1 = new javax.swing.JLabel();
        jComboBoxCiudad1 = new javax.swing.JComboBox<>();
        jLabelIsapre1 = new javax.swing.JLabel();
        jRadioButtonSi1 = new javax.swing.JRadioButton();
        jRadioButtonNo1 = new javax.swing.JRadioButton();
        jLabelDonante1 = new javax.swing.JLabel();
        jCheckBoxDondante1 = new javax.swing.JCheckBox();
        jButtonLimpiar1 = new javax.swing.JButton();
        jButtonSalir1 = new javax.swing.JButton();
        jButtonGuardar1 = new javax.swing.JButton();
        jInternalFrameListar = new javax.swing.JInternalFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePacientes = new javax.swing.JTable();
        jButtonEliminarPaciente = new javax.swing.JButton();
        jButtonModificarPaciente = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jTextFieldBuscaRut = new javax.swing.JTextField();
        jButtonBuscaRut = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuProcesos = new javax.swing.JMenu();
        jMenuItemAgregar = new javax.swing.JMenuItem();
        jMenuItemListar = new javax.swing.JMenuItem();
        jMenuItemSalir = new javax.swing.JMenuItem();
        jMenuAyuda = new javax.swing.JMenu();

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 23, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Consulta Médica");
        setName(""); // NOI18N
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jInternalFrameAgregar.setMaximizable(true);
        jInternalFrameAgregar.setResizable(true);
        jInternalFrameAgregar.setTitle("Agregar Paciente");
        jInternalFrameAgregar.setVisible(false);

        jLabelRut.setText("Rut: ");

        jTextFieldRut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldRutActionPerformed(evt);
            }
        });

        jLabelNombre.setText("Nombre: ");

        jLabelGenero.setText("Género: ");

        buttonGroup2.add(jRadioButtonMasculino);
        jRadioButtonMasculino.setText("Maculino");

        buttonGroup2.add(jRadioButtonFemenino1);
        jRadioButtonFemenino1.setText("Femenino");

        jLabelEdad.setText("Edad:");

        jLabelDireccion.setText("Dirección:");

        jLabelCiudad.setText("Ciudad:");

        jComboBoxCiudad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Santiago", "Concepción", "Valparaíso", "La Serena", "Temuco", "Antofagasta", "Iquique", "Rancagua", "Puerto Montt" }));
        jComboBoxCiudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCiudadActionPerformed(evt);
            }
        });

        jLabelIsapre.setText("Isapre:");

        buttonGroup1.add(jRadioButtonSi);
        jRadioButtonSi.setText("Si");

        buttonGroup1.add(jRadioButtonNo);
        jRadioButtonNo.setText("No");

        jLabelDonante.setText("Donante: ");

        jButtonLimpiar.setText("Limpiar");
        jButtonLimpiar.setMaximumSize(new java.awt.Dimension(76, 32));
        jButtonLimpiar.setMinimumSize(new java.awt.Dimension(76, 32));
        jButtonLimpiar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonLimpiarMouseClicked(evt);
            }
        });

        jButtonSalir.setText("Salir");
        jButtonSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonSalirMouseClicked(evt);
            }
        });

        jButtonGuardar.setText("Guardar");
        jButtonGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonGuardarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrameAgregarLayout = new javax.swing.GroupLayout(jInternalFrameAgregar.getContentPane());
        jInternalFrameAgregar.getContentPane().setLayout(jInternalFrameAgregarLayout);
        jInternalFrameAgregarLayout.setHorizontalGroup(
            jInternalFrameAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrameAgregarLayout.createSequentialGroup()
                .addGroup(jInternalFrameAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrameAgregarLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jInternalFrameAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelRut)
                            .addComponent(jLabelNombre)
                            .addComponent(jLabelEdad)
                            .addComponent(jLabelDireccion)
                            .addGroup(jInternalFrameAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabelIsapre)
                                .addComponent(jLabelCiudad))
                            .addGroup(jInternalFrameAgregarLayout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabelDonante))))
                    .addGroup(jInternalFrameAgregarLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabelGenero)))
                .addGap(51, 51, 51)
                .addGroup(jInternalFrameAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrameAgregarLayout.createSequentialGroup()
                        .addComponent(jRadioButtonFemenino1)
                        .addGap(34, 34, 34)
                        .addComponent(jRadioButtonMasculino))
                    .addComponent(jCheckBoxDondante)
                    .addComponent(jTextFieldDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jInternalFrameAgregarLayout.createSequentialGroup()
                        .addComponent(jRadioButtonSi)
                        .addGap(30, 30, 30)
                        .addComponent(jRadioButtonNo))
                    .addComponent(jComboBoxCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldRut, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 164, Short.MAX_VALUE)
                .addGroup(jInternalFrameAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonLimpiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                    .addComponent(jButtonSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(39, 39, 39))
        );
        jInternalFrameAgregarLayout.setVerticalGroup(
            jInternalFrameAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrameAgregarLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jInternalFrameAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jInternalFrameAgregarLayout.createSequentialGroup()
                        .addGroup(jInternalFrameAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelRut)
                            .addComponent(jTextFieldRut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jInternalFrameAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelNombre)
                            .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49))
                    .addGroup(jInternalFrameAgregarLayout.createSequentialGroup()
                        .addComponent(jButtonGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jInternalFrameAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonMasculino)
                    .addComponent(jRadioButtonFemenino1)
                    .addComponent(jButtonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelGenero))
                .addGap(46, 46, 46)
                .addGroup(jInternalFrameAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEdad)
                    .addComponent(jTextFieldEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jInternalFrameAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDireccion)
                    .addComponent(jTextFieldDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jInternalFrameAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCiudad)
                    .addComponent(jComboBoxCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jInternalFrameAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelIsapre)
                    .addGroup(jInternalFrameAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jRadioButtonSi)
                        .addComponent(jRadioButtonNo)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jInternalFrameAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBoxDondante)
                    .addComponent(jLabelDonante))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        getContentPane().add(jInternalFrameAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 740, 490));

        jInternalFrameModificar.setMaximizable(true);
        jInternalFrameModificar.setResizable(true);
        jInternalFrameModificar.setTitle("Agregar Paciente");
        jInternalFrameModificar.setVisible(false);

        jLabelRut1.setText("Rut: ");

        jTextFieldRut1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldRut1ActionPerformed(evt);
            }
        });

        jLabelNombre1.setText("Nombre: ");

        jLabelGenero1.setText("Género: ");

        buttonGroup2.add(jRadioButtonMasculino1);
        jRadioButtonMasculino1.setText("Maculino");

        buttonGroup2.add(jRadioButtonFemenino2);
        jRadioButtonFemenino2.setText("Femenino");

        jLabelEdad1.setText("Edad:");

        jLabelDireccion1.setText("Dirección:");

        jLabelCiudad1.setText("Ciudad:");

        jComboBoxCiudad1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Santiago", "Concepción", "Valparaíso", "La Serena", "Temuco", "Antofagasta", "Iquique", "Rancagua", "Puerto Montt" }));
        jComboBoxCiudad1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCiudad1ActionPerformed(evt);
            }
        });

        jLabelIsapre1.setText("Isapre:");

        buttonGroup1.add(jRadioButtonSi1);
        jRadioButtonSi1.setText("Si");

        buttonGroup1.add(jRadioButtonNo1);
        jRadioButtonNo1.setText("No");

        jLabelDonante1.setText("Donante: ");

        jButtonLimpiar1.setText("Limpiar");
        jButtonLimpiar1.setMaximumSize(new java.awt.Dimension(76, 32));
        jButtonLimpiar1.setMinimumSize(new java.awt.Dimension(76, 32));
        jButtonLimpiar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonLimpiar1MouseClicked(evt);
            }
        });

        jButtonSalir1.setText("Salir");
        jButtonSalir1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonSalir1MouseClicked(evt);
            }
        });

        jButtonGuardar1.setText("Guardar");
        jButtonGuardar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonGuardar1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrameModificarLayout = new javax.swing.GroupLayout(jInternalFrameModificar.getContentPane());
        jInternalFrameModificar.getContentPane().setLayout(jInternalFrameModificarLayout);
        jInternalFrameModificarLayout.setHorizontalGroup(
            jInternalFrameModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrameModificarLayout.createSequentialGroup()
                .addGroup(jInternalFrameModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrameModificarLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jInternalFrameModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelRut1)
                            .addComponent(jLabelNombre1)
                            .addComponent(jLabelEdad1)
                            .addComponent(jLabelDireccion1)
                            .addGroup(jInternalFrameModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabelIsapre1)
                                .addComponent(jLabelCiudad1))
                            .addGroup(jInternalFrameModificarLayout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabelDonante1))))
                    .addGroup(jInternalFrameModificarLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabelGenero1)))
                .addGap(51, 51, 51)
                .addGroup(jInternalFrameModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrameModificarLayout.createSequentialGroup()
                        .addComponent(jRadioButtonFemenino2)
                        .addGap(34, 34, 34)
                        .addComponent(jRadioButtonMasculino1))
                    .addComponent(jCheckBoxDondante1)
                    .addComponent(jTextFieldDireccion1, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jInternalFrameModificarLayout.createSequentialGroup()
                        .addComponent(jRadioButtonSi1)
                        .addGap(30, 30, 30)
                        .addComponent(jRadioButtonNo1))
                    .addComponent(jComboBoxCiudad1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldRut1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldEdad1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 134, Short.MAX_VALUE)
                .addGroup(jInternalFrameModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonLimpiar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonGuardar1, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                    .addComponent(jButtonSalir1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(39, 39, 39))
        );
        jInternalFrameModificarLayout.setVerticalGroup(
            jInternalFrameModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrameModificarLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jInternalFrameModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jInternalFrameModificarLayout.createSequentialGroup()
                        .addGroup(jInternalFrameModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelRut1)
                            .addComponent(jTextFieldRut1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jInternalFrameModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelNombre1)
                            .addComponent(jTextFieldNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49))
                    .addGroup(jInternalFrameModificarLayout.createSequentialGroup()
                        .addComponent(jButtonGuardar1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonLimpiar1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jInternalFrameModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonMasculino1)
                    .addComponent(jRadioButtonFemenino2)
                    .addComponent(jButtonSalir1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelGenero1))
                .addGap(46, 46, 46)
                .addGroup(jInternalFrameModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEdad1)
                    .addComponent(jTextFieldEdad1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jInternalFrameModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDireccion1)
                    .addComponent(jTextFieldDireccion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jInternalFrameModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCiudad1)
                    .addComponent(jComboBoxCiudad1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jInternalFrameModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelIsapre1)
                    .addGroup(jInternalFrameModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jRadioButtonSi1)
                        .addComponent(jRadioButtonNo1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jInternalFrameModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBoxDondante1)
                    .addComponent(jLabelDonante1))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        getContentPane().add(jInternalFrameModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 710, 490));

        jInternalFrameListar.setTitle("Listar Pacientes");
        jInternalFrameListar.setVisible(false);

        jTablePacientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTablePacientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablePacientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTablePacientes);

        jButtonEliminarPaciente.setText("Eliminar");
        jButtonEliminarPaciente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonEliminarPacienteMouseClicked(evt);
            }
        });

        jButtonModificarPaciente.setText("Modificar");
        jButtonModificarPaciente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonModificarPacienteMouseClicked(evt);
            }
        });

        jButton1.setText("Cerrar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jTextFieldBuscaRut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBuscaRutActionPerformed(evt);
            }
        });

        jButtonBuscaRut.setText("Buscar");
        jButtonBuscaRut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonBuscaRutMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Buscar por Rut Paciente");

        javax.swing.GroupLayout jInternalFrameListarLayout = new javax.swing.GroupLayout(jInternalFrameListar.getContentPane());
        jInternalFrameListar.getContentPane().setLayout(jInternalFrameListarLayout);
        jInternalFrameListarLayout.setHorizontalGroup(
            jInternalFrameListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrameListarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(jInternalFrameListarLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jButtonEliminarPaciente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonModificarPaciente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(46, 46, 46))
            .addGroup(jInternalFrameListarLayout.createSequentialGroup()
                .addGap(195, 195, 195)
                .addGroup(jInternalFrameListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jInternalFrameListarLayout.createSequentialGroup()
                        .addComponent(jTextFieldBuscaRut, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonBuscaRut)))
                .addContainerGap(219, Short.MAX_VALUE))
        );
        jInternalFrameListarLayout.setVerticalGroup(
            jInternalFrameListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrameListarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jInternalFrameListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldBuscaRut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBuscaRut))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addGroup(jInternalFrameListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonEliminarPaciente)
                    .addComponent(jButtonModificarPaciente)
                    .addComponent(jButton1))
                .addGap(22, 22, 22))
        );

        getContentPane().add(jInternalFrameListar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 750, -1));

        jMenuProcesos.setText("Procesos");
        jMenuProcesos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuProcesosMouseClicked(evt);
            }
        });
        jMenuProcesos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuProcesosActionPerformed(evt);
            }
        });

        jMenuItemAgregar.setText("Agregar");
        jMenuItemAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAgregarActionPerformed(evt);
            }
        });
        jMenuProcesos.add(jMenuItemAgregar);

        jMenuItemListar.setText("Listar");
        jMenuItemListar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItemListarMouseClicked(evt);
            }
        });
        jMenuItemListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemListarActionPerformed(evt);
            }
        });
        jMenuProcesos.add(jMenuItemListar);

        jMenuItemSalir.setText("Salir");
        jMenuItemSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItemSalirMouseClicked(evt);
            }
        });
        jMenuItemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSalirActionPerformed(evt);
            }
        });
        jMenuProcesos.add(jMenuItemSalir);

        jMenuBar1.add(jMenuProcesos);

        jMenuAyuda.setText("Ayuda");
        jMenuAyuda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuAyudaMouseClicked(evt);
            }
        });
        jMenuAyuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAyudaActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenuAyuda);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAgregarActionPerformed
        jInternalFrameAgregar.setVisible(true);     // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemAgregarActionPerformed

    private void jMenuProcesosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuProcesosMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuProcesosMouseClicked

    private void jTextFieldRutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldRutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldRutActionPerformed

    private void jComboBoxCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCiudadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxCiudadActionPerformed

    private void jMenuItemSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItemSalirMouseClicked

        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemSalirMouseClicked

    private void jMenuItemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSalirActionPerformed
        int respuesta = JOptionPane.showConfirmDialog(this, "Seguro?", "Atencion", JOptionPane.INFORMATION_MESSAGE);
        if (respuesta == 0) {
            System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemSalirActionPerformed
    }
    private void jButtonSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSalirMouseClicked
        jInternalFrameAgregar.setVisible(false);
    }//GEN-LAST:event_jButtonSalirMouseClicked

    private void jButtonGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonGuardarMouseClicked
        Paciente paciente = new Paciente();
        Registro registro = new Registro();
        if (!jTextFieldRut.getText().isEmpty()) {
            paciente.setRut(jTextFieldRut.getText());
        } else {
            JOptionPane.showMessageDialog(this, "El rut no puede estar vacio", "atencion", JOptionPane.WARNING_MESSAGE);
        }
        if (!jTextFieldNombre.getText().isEmpty()) {
            paciente.setNombreCompleto(jTextFieldNombre.getText());
        } else {
            JOptionPane.showMessageDialog(this, "El nombre no puede estar vacio", "atencion", JOptionPane.WARNING_MESSAGE);
        }

        if (jRadioButtonFemenino1.isSelected()) {

            paciente.setGenero("F");
        }
        if (jRadioButtonMasculino.isSelected()) {

            paciente.setGenero("M");
        }
        if (!jTextFieldEdad.getText().isEmpty()) {
            try {
                paciente.setEdad(Integer.parseInt(jTextFieldEdad.getText()));
            } catch (NumberFormatException error) {
                JOptionPane.showMessageDialog(this, "Edad no validad", "Atención", JOptionPane.WARNING_MESSAGE);
            }

        } else {
            JOptionPane.showMessageDialog(this, "La edad no puede estar vacio", "atencion", JOptionPane.WARNING_MESSAGE);
        }

        if (!jTextFieldDireccion.getText().isEmpty()) {
            paciente.setDireccion(jTextFieldDireccion.getText());

        } else {
            JOptionPane.showMessageDialog(this, "La direccion no puede estar vacio", "atencion", JOptionPane.WARNING_MESSAGE);
        }
        paciente.setCiudad(jComboBoxCiudad.getSelectedItem().toString());
        if (jRadioButtonSi.isSelected()) {
            paciente.setIsapre("S");
        }
        if (jRadioButtonNo.isSelected()) {
            paciente.setIsapre("N");
        }
        if (jCheckBoxDondante.isSelected()) {
            paciente.setDonante(true);
        } else {
            paciente.setDonante(false);
        }

        if (paciente.getEdad() != 0) {
            int rowAffected = registro.agrega(paciente);

            if (rowAffected == 1) {
                JOptionPane.showMessageDialog(this, "Paciente registrado exitosamente", "Atencion", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Paciente no fue registrado ", "Atencion", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Paciente no fue registrado ", "Atencion", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonGuardarMouseClicked

    private void jButtonLimpiarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonLimpiarMouseClicked
        jTextFieldRut.setText("");
        jTextFieldNombre.setText("");
        buttonGroup1.clearSelection();
        jTextFieldEdad.setText("");
        jTextFieldDireccion.setText("");
        jComboBoxCiudad.setSelectedIndex(0);
        buttonGroup2.clearSelection();
        jCheckBoxDondante.setSelected(false);
        jTextFieldRut.requestFocus();
    }//GEN-LAST:event_jButtonLimpiarMouseClicked

    private void jMenuItemListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemListarActionPerformed
        jInternalFrameListar.setVisible(true);
        this.mostrarTabla(jTablePacientes);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemListarActionPerformed

    private void jMenuProcesosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuProcesosActionPerformed

// TODO add your handling code here:
    }//GEN-LAST:event_jMenuProcesosActionPerformed

    private void jMenuItemListarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItemListarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemListarMouseClicked

    private void jTablePacientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablePacientesMouseClicked
        this.mostrarTabla(jTablePacientes);

    }//GEN-LAST:event_jTablePacientesMouseClicked

    private void jButtonEliminarPacienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonEliminarPacienteMouseClicked
        int rowSelected = jTablePacientes.getSelectedRow();
        String rut = (String) jTablePacientes.getValueAt(rowSelected, 0);
        Registro registro = new Registro();
        Paciente p = registro.buscarPorRut(rut);
        registro.elimina(p);
        JOptionPane.showMessageDialog(this, "Paciente borrado correctamente", "Atencion", JOptionPane.INFORMATION_MESSAGE);
        this.mostrarTabla(jTablePacientes);
    }//GEN-LAST:event_jButtonEliminarPacienteMouseClicked

    private void jButtonModificarPacienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonModificarPacienteMouseClicked
        int rowSelected = jTablePacientes.getSelectedRow();
        if (rowSelected != -1) {
            String rut = (String) jTablePacientes.getValueAt(rowSelected, 0);
            String nombre = (String) jTablePacientes.getValueAt(rowSelected, 1);
            String genero = (String) jTablePacientes.getValueAt(rowSelected, 2);
            int edad = (int) jTablePacientes.getValueAt(rowSelected, 3);
            String direccion = (String) jTablePacientes.getValueAt(rowSelected, 4);
            String ciudad = (String) jTablePacientes.getValueAt(rowSelected, 5);
            String isapre = (String) jTablePacientes.getValueAt(rowSelected, 6);
            boolean dondante = (boolean) jTablePacientes.getValueAt(rowSelected, 7);
            jTextFieldRut1.setText(rut);
            jTextFieldRut1.setEditable(false);
            jTextFieldNombre1.setText(nombre);
            if (genero.equals("F")) {
                jRadioButtonFemenino2.setSelected(true);
            }
            if (genero.equals("M")) {
                jRadioButtonMasculino1.setSelected(true);
            }

            jTextFieldEdad1.setText(Integer.toString(edad));

            jTextFieldDireccion1.setText(direccion);

            jComboBoxCiudad1.setSelectedItem(ciudad);
            if (isapre.equals("S")) {
                jRadioButtonSi1.setSelected(true);
            }
            if (isapre.equals("N")) {
                jRadioButtonNo1.setSelected(true);
            }

            jCheckBoxDondante1.setSelected(dondante);

            jInternalFrameModificar.setVisible(true);
        }else
            JOptionPane.showMessageDialog(this, "Debes seleccionar una fila para modificar", "atencion", JOptionPane.WARNING_MESSAGE);


    }//GEN-LAST:event_jButtonModificarPacienteMouseClicked

    private void jTextFieldRut1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldRut1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldRut1ActionPerformed

    private void jComboBoxCiudad1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCiudad1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxCiudad1ActionPerformed

    private void jButtonLimpiar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonLimpiar1MouseClicked
        jTextFieldRut1.setText("");
        jTextFieldNombre1.setText("");
        buttonGroup1.clearSelection();
        jTextFieldEdad1.setText("");
        jTextFieldDireccion1.setText("");
        jComboBoxCiudad1.setSelectedIndex(0);
        buttonGroup2.clearSelection();
        jCheckBoxDondante1.setSelected(false);
        jTextFieldRut1.requestFocus();        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonLimpiar1MouseClicked

    private void jButtonSalir1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSalir1MouseClicked
        jInternalFrameModificar.setVisible(false);                // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSalir1MouseClicked

    private void jButtonGuardar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonGuardar1MouseClicked
        Paciente paciente = new Paciente();
        Registro registro = new Registro();
        if (!jTextFieldRut1.getText().isEmpty()) {
            paciente.setRut(jTextFieldRut1.getText());
        } else {
            JOptionPane.showMessageDialog(this, "El rut no puede estar vacio", "atencion", JOptionPane.WARNING_MESSAGE);
        }
        if (!jTextFieldNombre1.getText().isEmpty()) {
            paciente.setNombreCompleto(jTextFieldNombre1.getText());
        } else {
            JOptionPane.showMessageDialog(this, "El nombre no puede estar vacio", "atencion", JOptionPane.WARNING_MESSAGE);
        }

        if (jRadioButtonFemenino2.isSelected()) {

            paciente.setGenero("F");
        }
        if (jRadioButtonMasculino1.isSelected()) {

            paciente.setGenero("M");
        }
        if (!jTextFieldEdad1.getText().isEmpty()) {
            try {
                paciente.setEdad(Integer.parseInt(jTextFieldEdad1.getText()));
            } catch (NumberFormatException error) {
                JOptionPane.showMessageDialog(this, "Edad no validad", "Atención", JOptionPane.INFORMATION_MESSAGE);
            }

        } else {
            JOptionPane.showMessageDialog(this, "La edad no puede estar vacio", "atencion", JOptionPane.WARNING_MESSAGE);
        }

        if (!jTextFieldDireccion1.getText().isEmpty()) {
            paciente.setDireccion(jTextFieldDireccion1.getText());

        } else {
            JOptionPane.showMessageDialog(this, "La direccion no puede estar vacio", "atencion", JOptionPane.WARNING_MESSAGE);
        }
        paciente.setCiudad(jComboBoxCiudad1.getSelectedItem().toString());
        if (jRadioButtonSi1.isSelected()) {
            paciente.setIsapre("S");
        }
        if (jRadioButtonNo1.isSelected()) {
            paciente.setIsapre("N");
        }
        if (jCheckBoxDondante1.isSelected()) {
            paciente.setDonante(true);
        } else {
            paciente.setDonante(false);
        }
        if (paciente.getEdad() != 0) {
            int rowAffected = registro.modificar(paciente);

            if (rowAffected == 1) {
                JOptionPane.showMessageDialog(this, "Paciente modificado exitosamente", "Atencion", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Paciente no fue modificado ", "Atencion", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Paciente no fue modificado ", "Atencion", JOptionPane.ERROR_MESSAGE);
        }
        this.mostrarTabla(jTablePacientes);// TODO add your handling code here:
    }//GEN-LAST:event_jButtonGuardar1MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        jInternalFrameListar.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseClicked

    private void jTextFieldBuscaRutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBuscaRutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBuscaRutActionPerformed

    private void jButtonBuscaRutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonBuscaRutMouseClicked
        Registro registro = new Registro();
        Paciente p = registro.buscarPorRut(jTextFieldBuscaRut.getText());
        if (p != null) {
            this.mostrarTablaPorRut(jTablePacientes);
        } else {
            JOptionPane.showMessageDialog(this, "El paciente ingresado no existe", "atención", JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_jButtonBuscaRutMouseClicked

    private void jMenuAyudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAyudaActionPerformed
              // TODO add your handling code here:
    }//GEN-LAST:event_jMenuAyudaActionPerformed

    private void jMenuAyudaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuAyudaMouseClicked
        JOptionPane.showMessageDialog(this, "Trabajando para poder otorgarte ayuda", "Ayuda", JOptionPane.INFORMATION_MESSAGE);  // TODO add your handling code here:
    }//GEN-LAST:event_jMenuAyudaMouseClicked
    private void mostrarTabla(JTable tabla) {
        Object[] titulo = {"Rut", "Nombre Completo", "Genero", "Edad", "Direccion", "Ciudad", "Isapre", "Donante"};
        Registro registro = new Registro();
        DefaultTableModel dfm = new DefaultTableModel();
        dfm.setColumnIdentifiers(titulo);
        ArrayList<Paciente> pacientes = registro.buscarTodos();
        for (Paciente p : pacientes) {
            dfm.addRow(new Object[]{p.getRut(), p.getNombreCompleto(), p.getGenero(), p.getEdad(), p.getDireccion(), p.getCiudad(), p.getIsapre(), p.isDonante()});
        }
        tabla.setModel(dfm);
    }

    private void mostrarTablaPorRut(JTable tabla) {
        Object[] titulo = {"Rut", "Nombre Completo", "Genero", "Edad", "Direccion", "Ciudad", "Isapre", "Donante"};
        Registro registro = new Registro();
        Paciente p = new Paciente();
        DefaultTableModel dfm = new DefaultTableModel();
        dfm.setColumnIdentifiers(titulo);
        p = registro.buscarPorRut(jTextFieldBuscaRut.getText());

        dfm.addRow(new Object[]{p.getRut(), p.getNombreCompleto(), p.getGenero(), p.getEdad(), p.getDireccion(), p.getCiudad(), p.getIsapre(), p.isDonante()});

        tabla.setModel(dfm);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonBuscaRut;
    private javax.swing.JButton jButtonEliminarPaciente;
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JButton jButtonGuardar1;
    private javax.swing.JButton jButtonLimpiar;
    private javax.swing.JButton jButtonLimpiar1;
    private javax.swing.JButton jButtonModificarPaciente;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JButton jButtonSalir1;
    private javax.swing.JCheckBox jCheckBoxDondante;
    private javax.swing.JCheckBox jCheckBoxDondante1;
    private javax.swing.JComboBox<String> jComboBoxCiudad;
    private javax.swing.JComboBox<String> jComboBoxCiudad1;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JInternalFrame jInternalFrameAgregar;
    private javax.swing.JInternalFrame jInternalFrameListar;
    private javax.swing.JInternalFrame jInternalFrameModificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelCiudad;
    private javax.swing.JLabel jLabelCiudad1;
    private javax.swing.JLabel jLabelDireccion;
    private javax.swing.JLabel jLabelDireccion1;
    private javax.swing.JLabel jLabelDonante;
    private javax.swing.JLabel jLabelDonante1;
    private javax.swing.JLabel jLabelEdad;
    private javax.swing.JLabel jLabelEdad1;
    private javax.swing.JLabel jLabelGenero;
    private javax.swing.JLabel jLabelGenero1;
    private javax.swing.JLabel jLabelIsapre;
    private javax.swing.JLabel jLabelIsapre1;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelNombre1;
    private javax.swing.JLabel jLabelRut;
    private javax.swing.JLabel jLabelRut1;
    private javax.swing.JMenu jMenuAyuda;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemAgregar;
    private javax.swing.JMenuItem jMenuItemListar;
    private javax.swing.JMenuItem jMenuItemSalir;
    private javax.swing.JMenu jMenuProcesos;
    private javax.swing.JRadioButton jRadioButtonFemenino1;
    private javax.swing.JRadioButton jRadioButtonFemenino2;
    private javax.swing.JRadioButton jRadioButtonMasculino;
    private javax.swing.JRadioButton jRadioButtonMasculino1;
    private javax.swing.JRadioButton jRadioButtonNo;
    private javax.swing.JRadioButton jRadioButtonNo1;
    private javax.swing.JRadioButton jRadioButtonSi;
    private javax.swing.JRadioButton jRadioButtonSi1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablePacientes;
    private javax.swing.JTextField jTextFieldBuscaRut;
    private javax.swing.JTextField jTextFieldDireccion;
    private javax.swing.JTextField jTextFieldDireccion1;
    private javax.swing.JTextField jTextFieldEdad;
    private javax.swing.JTextField jTextFieldEdad1;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldNombre1;
    private javax.swing.JTextField jTextFieldRut;
    private javax.swing.JTextField jTextFieldRut1;
    // End of variables declaration//GEN-END:variables
}
