//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Controlador
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLEADO
    {
        public decimal IDEMPLEADO { get; set; }
        public string NOMBREEMPLEADO { get; set; }
        public string APELLIDOEMPLEADO { get; set; }
        public string RUTEMPELADO { get; set; }
        public string ESTADOCIVIL { get; set; }
    }
}
